#!/usr/bin/bash

# This file both starts the Nubb++ compiler and build the final executable at once by using g++.

# You will need the nubb.exe compiler executable for this to work, as well as g++, which you can install here:
# https://code.visualstudio.com/docs/cpp/config-mingw (skip past installing VSC and the C++ extension, just install MinGW)

# Feel free to make suggestions on improving this script as well, since I'm a massive noob with bash scripting
# I might implement all of this into the compiler by default just so less stuff has to be done but we'll see xD

./nubb++.exe $1
echo "" # newline

# if script ran successfully then we compile to c++ and run the executable
if [ $? == 0 ]; then
    g++ -o nubb.out out.cpp
else
    echo "[FATAL] Nubb++ failed to build executable."
    echo "[WARN] Given filename to build: $1"
    echo "[WARN] Ensure g++ is properly installed. Use 'g++ --version' to check installation."
    echo "[WARN] Syntax: ./nubb++build [filepath]"
fi 
